name: Bare Run on various PHP versions

on:
    push:
        branches:
            - main

jobs:
    bare_run:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

        steps:
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -   run: composer require tomasvotruba/class-leak

            -   run: vendor/bin/class-leak list --ansi
